### ISSUE TITLE
Feature: User can search a pokémon and view the search result

### ISSUE THREAD

**Issue by samlee0258** [samlee0258/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can search a pokemon and view the search result.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Create a home page with a search bar that allows users to search for a pokemon by name and view the pokemon's name, type, and basic stats. The search button in the nav bar brings the home page back up so the user can search for another pokemon. The web page should have a responsive display for mobile and desktop.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="739" alt="Screenshot 2023-03-01 at 11 29 01 AM" src="https://user-images.githubusercontent.com/110208589/222244917-f7f1ce6d-3ac4-445e-855a-020c48bc76ea.png">
<img width="895" alt="Screenshot 2023-03-01 at 11 31 28 AM" src="https://user-images.githubusercontent.com/110208589/222245090-25266e47-8e7b-4500-9287-f4ead1448f59.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create the HTML for the home page, and link all necessary files to the html skeleton.
    - [x]  Create `styles.css` file and link to HTML.
    - [x]  Create `layout.css` file and link to HTML.
    - [x]  Create `main.js` file and link to HTML.
    - [x]  Create `data.js` file and link to HTML.

- [x]  Create different `data-view=""` on `div` elements to specify which page you are viewing. 

- [x]  Complete the HTML using the appropriate responsive layout classes.
    - [x]  Write CSS for mobile devices first.
    - [x]  Adjust styling to fluidly adapt to desktop.

- [x]  Add necessary elements in the html so that it matches the format of the example figma.
    - [x]  Add nav bar with the name of the app and search `<a>` tag.
    - [x]  Add Title to the home search page.
    - [x]  Create a search `'input'` with a search button.
    - [x]  Add pokéball image onto the home search page.
    - [x]  Add `id="home-page"`.

- [x]  Add CSS styling to match the example image in the figma.

- [x] In `main.js` create a function to get pokémon data.
    - [x]  Create variable `xhr` and assign it a `new XMLHttpRequest()`.
    - [x]  Assign `'json'` to `xhr.responseType`.
    - [x]  Add `'load'` event listener to `xhr` with a function to `console.log(xhr.status)` and `console.log(xhr.response)`.
    - [x]  Call `xhr.send( )` with no argument. 

- [x]  Create the structure of the search result page to match the example figma with the class `hidden` when finished.

- [x]  In `main.js` add an event listener to the search button:
    - [x]  When clicked change the `className` of the search result page to `class="search-result"`.
    - [x]  Change the `className` to the home search page to `hidden`.

- [x]  In `data.js` create a data model that holds the information retrieved from the function that gets the pokémon's data when searched.

- [x]  On the search result page:
    - [x]  Have a header with `Search Result`.
    - [x]  Display image of the searched pokémon.
    - [x]  Display heading with name.
    - [x]  Display type of the searched pokémon and icon of the type on the left side of text, similar to the example figma.
    - [x]  Display heading with text `Base Stats`.
    - [x]  Display hp, atk, def, sp-atk, sp-def, and speed with their respective values.

- [x]  In `main.js` add a 'click' event listener to the search `<a>` tag on the nav bar.
    - [x]  When clicked the home search page is shown.

- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
