### ISSUE TITLE
Feature: User can view their list of favorite pokémons

### ISSUE THREAD

**Issue by samlee0258** [samlee0258/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User has a favorites tab where they can view their saved pokémons which they will be able to save in the next issue.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Create a favorite tab on the nav bar so that user can click view their favorite's list.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="739" alt="Screenshot 2023-03-01 at 11 37 41 AM" src="https://user-images.githubusercontent.com/110208589/222246302-0a6ae00c-5a0a-486b-9fdb-8363c48d0e79.png">
<img width="892" alt="Screenshot 2023-03-01 at 11 38 11 AM" src="https://user-images.githubusercontent.com/110208589/222246338-2259f8dd-59a5-42ff-b70a-9e2d729ccaad.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a `div[data-view="favorites"]` element in the HTML.
- [x] Add a `<a>` tag to the nav bar named "Favorites".
- [x] In `main.js` add to the function `viewSwap`:
  - [x] query for the favorites data view and assign to a variable in a global scope
  - [x] if `data.view` equals 'favorites' change the className for `home-page` and `search-result` to `hidden`.
  - [x] if `data.view` equals either `home-page` or `search-result` change className of `favorites` to `hidden`.
- [x] Write a message in the `index.html` file indicating that no pokemon has been added to the favorite's list.

- **Clean Up**
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
