### ISSUE TITLE
Feature: User can save the pokémon to a favorites list

### ISSUE THREAD

**Issue by samlee0258** [samlee0258/ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can save their searched pokémon into their favorites list.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

In the favorite's list the saved entries will be viewed from most recently added.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="734" alt="Screenshot 2023-03-01 at 11 39 53 AM" src="https://user-images.githubusercontent.com/110208589/222247061-53880c3c-05f6-4fdf-b892-442e3282b111.png">
<img width="922" alt="Screenshot 2023-03-01 at 11 41 06 AM" src="https://user-images.githubusercontent.com/110208589/222247078-364587c4-ef14-49c5-8155-fe072c56e09b.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

 - [x] Add a button to the search result page.
   - [x] Add styling to the button to look like the figma example.

 - [ ] In main.js file query select the button.
   - [ ] Add an event listener function to the button so that when `clicked` it creates a DOM in the favorites page.
   - [ ] Update `viewSwap` function so that when pokemon is added it changes view to the favorites.
   - [ ] Save the favorited pokemon to `localStorage` with an `entryId`.
   - [ ] Increment the `nextDataId` by 1 so that the next saved pokemon has a different number.
   - [ ] Newest saved pokemons are shown on top.

- [ ] Create a function named `toggleNoPokemon` which toggles the no pokemon text to show or hide when the function is called.

- [x] In data.js, add a 'beforeunload' event listener to the window object that serializes the data model as JSON and stores the JSON in localStorage.
- [x] At the bottom of data.js, include a conditional statement that:
   - [x] checks to see if there is a JSON data model stored in localStorage.
   - [x] if there is, parse it and assign it to the initial data variable so that the user can continue adding entries to the pre-existing data model.

- [ ] Test the app by adding pokemons to the favorites and then reloading the page to confirm that:
   - [ ] the data model is being saved to localStorage before each page reload.
   - [ ] each new pokemon object is receiving an incrementing entryId property.

- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
