### ISSUE TITLE
Feature: User can remove pokémons from the favorites list

### ISSUE THREAD

**Issue by samlee0258** [samlee0258/ajax-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

If the user no longer likes a saved pokémon in their favorite's list will be able to remove it.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Allow user to delete a saved pokémon from their favorites list. 
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="734" alt="Screenshot 2023-03-01 at 11 42 06 AM" src="https://user-images.githubusercontent.com/110208589/222247465-45bef5a8-9ac3-4ac0-abd5-878108304bff.png">
<img width="926" alt="Screenshot 2023-03-01 at 11 42 29 AM" src="https://user-images.githubusercontent.com/110208589/222247489-57a477d9-fda3-4996-b4e0-364fdf8455c7.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
