### ISSUE TITLE
Feature: User can filter favorite pokémons by type

### ISSUE THREAD

**Issue by samlee0258** [samlee0258/ajax-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

When user has more than one pokémons in their favorites list they can filter through their list by types so that it's easier for them to view through their list.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When checking a type in the filter modal it looks through the list of favorite pokémons and shows the one the user wants to see.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="733" alt="Screenshot 2023-03-01 at 11 44 05 AM" src="https://user-images.githubusercontent.com/110208589/222247892-bc254520-eaa4-4263-9ec0-f866ef6ab9ff.png">
<img width="927" alt="Screenshot 2023-03-01 at 11 44 26 AM" src="https://user-images.githubusercontent.com/110208589/222247923-c8996b3a-ac63-4fa1-84a9-20808e1888e0.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
